from crewai import Task


def get_convert_tutorial_to_html_format_task() -> Task:
    """Task for converting the tutorial book to HTML-ready format."""
    return Task(
        description="""Convert the compiled tutorial book into a professionally structured HTML 
    document for {topic}. Deliver a complete `<html>` document (including `<head>` and `<body>`) that:

1. **Page Structure**: Builds a landing section, an autogenerated table of contents with anchor links, chapter/appendix sections, glossary, resources, and assessments. Each major block must have semantic tags (`<header>`, `<nav>`, `<main>`, `<section>`, `<article>`, `<aside>`, `<footer>`).
2. **Accessible Styling**: Embed a `<style>` block in the `<head>` that defines a modern, responsive, and accessible theme. Use CSS variables, a readable font stack, high-contrast color palette that works in light/dark, generous spacing, responsive typography, styled callouts (`.callout-info`, `.callout-warning`, etc.), and polished tables/lists/code blocks.
3. **Navigation Aids**: Provide a persistent top navigation bar, breadcrumb-style chapter headers, in-page anchors, and back-to-top links for long sections.
4. **Responsive Layout**: Ensure grid/flex layouts collapse gracefully on phones. Include utility classes for two-column layouts that stack on small viewports, and style images/media with `.media-frame` wrappers.
5. **Reusable Components**: Define CSS classes for reusable widgets (e.g., `.learning-objective`, `.checklist`, `.tip`, `.assessment-card`). Reference them throughout to keep styling consistent.
6. **Chapter Quizzes**: Immediately following each chapter section, render a short quiz using semantic markup (`<section class="chapter-quiz">`). Each quiz must include at least five questions (mix of multiple choice, true/false, or short answer), accessible form controls, and an answer key reveal styled with the reusable components.
7. **Enhancements**: Add subtle transitions, focus states, and skip-link for accessibility. No external CSS/JS—everything must live in this single file.

Include all book components: introduction, chapters, resources, glossary, appendices, assessments, and any summary sections. Ensure the final HTML reads like a polished tutorial site and is immediately viewable from `outputs/{topic}_tutorial.html`.""",
        expected_output="""A single HTML document with head, embedded CSS, and body. It must include:
- Responsive layout with CSS variables and accessible color contrasts
- Semantic sections for landing page, table of contents, chapters, appendices, glossary, resources, and assessments
- Styled components (callouts, code blocks, tables, checklists, assessment cards) using reusable CSS classes
- A numbered quiz section after every chapter, with at least five questions and a styled answer key reveal
- Internal navigation links, back-to-top anchors, and a skip link for accessibility
- No external dependencies; everything self-contained in the saved file""",
        output_file="outputs/{topic}_tutorial.html",
        agent=None,
    )
